### ISSUE TITLE
DS1 issue

### ISSUE THREAD

**Issue by blisboabr** [whatisaphone/war#2]
Hi! I'm Bruno. I just saw your post about a darksiders save editor but the post its closed so I came here to talk to you. I dont know if you can help but this is the story: I was playing all normal, and at some point on the Black Throne I save the game and quit the game. Later when I came back, I was stucked between two locked doors (the part where you have to redirect a light beam to release the angel of death). In short, I'm stucked at this point, the game dont provide a way to restart the mission and my saves are at the same point. The save editor you posted might help me with this? Like spawn somewhere else. I dont have any experience with programming and I'm kind of lost. I appreciate if you could give me some light.

**Comment by whatisaphone** [comment]
If you're on the Warmastered Edition on Steam, I recommend you try out [my other project](https://github.com/whatisaphone/war-is-here). The /move_player or /infinite_jump commands might be able to help.

**Comment by vaidd4** [comment]
@blisboabr It might be a bit late but you might wanna checkout [this solution](https://github.com/whatisaphone/war/issues/5) I wrote for your problem.
